version: '3.8'

services:
  shop_app:
    build:
      context: .  
      dockerfile: Dockerfile
    
    ports:
      - "8080:80"
    
    depends_on:
      postgres_db

    command: /bin/bash -c "sleep 15 && dotnet Shop.dll"
      
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5433;Database=Sweet_Shop;Username=postgres;Password=12345
      - ASPNETCORE_ENVIRONMENT=Production
      
    restart: on-failure
    
  postgres_db:
    image: postgres:15-alpine
    ports:
      - "5433:5433" 
    environment:
      POSTGRES_DB: Sweet_Shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Sweet_Shop"]
      interval: 5s  
      timeout: 5s  
      retries: 10  
      start_period: 10s 
      
    restart: always

volumes:
  postgres_data: